# Generated by Django 6.0.2 on 2026-04-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("second_name", models.CharField(max_length=50)),
                ("student_id", models.IntegerField()),
            ],
            options={
                "db_table": "student2",
            },
        ),
    ]
