# Generated by Django 6.0.2 on 2026-04-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelapp", "0002_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="id",
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
