# Generated by Django 6.0.2 on 2026-04-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelapp", "0003_remove_student_id_alter_student_student_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=22)),
                ("email", models.EmailField(max_length=254)),
                ("date", models.DateField()),
                (
                    "ratings",
                    models.CharField(
                        choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
