# Generated by Django 6.0.2 on 2026-04-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelapp", "0004_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Runner2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "medal",
                    models.CharField(
                        choices=[
                            ("Gold", "Gold"),
                            ("Silver", "Silver"),
                            ("Bronze", "Bronze"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
        ),
    ]
