# Generated by Django 6.0.2 on 2026-04-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelapp", "0005_runner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fruit2",
            fields=[
                (
                    "name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
