# Generated by Django 6.0.2 on 2026-04-18 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modelapp", "0007_group_membership_group_members_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="membership",
            name="unique_person_group",
        ),
        migrations.RemoveField(
            model_name="group",
            name="members",
        ),
        migrations.DeleteModel(
            name="Membership",
        ),
    ]
