# Generated by Django 6.0.2 on 2026-04-18 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelapp", "0008_remove_membership_unique_person_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_joined", models.DateField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="modelapp.group"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modelapp.person",
                    ),
                ),
            ],
            options={
                "db_table": "new_membership",
                "ordering": ["date_joined"],
                "unique_together": {("person", "group")},
            },
        ),
    ]
