# Generated by Django 6.0.2 on 2026-04-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelapp", "0009_newmembership"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NewMembership",
            new_name="Membership",
        ),
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                through="modelapp.Membership", to="modelapp.person"
            ),
        ),
    ]
