# Generated by Django 6.0.2 on 2026-05-19 12:52

import cards.models
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CardsInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "card_name",
                    models.CharField(max_length=50, verbose_name="Card name"),
                ),
                (
                    "card_category",
                    models.CharField(max_length=50, verbose_name="Card categor"),
                ),
                ("card_description", models.TextField()),
                ("card_image", models.ImageField(upload_to=cards.models.card_img_path)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("card_name"),
                        name="unique_card_name_case_insensitive",
                    )
                ],
            },
        ),
    ]
