# Generated by Django 6.0.2 on 2026-05-12 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_tutorial", "0002_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="post",
        ),
        migrations.AddField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="model_tutorial.user",
            ),
        ),
    ]
