# Generated by Django 6.0.2 on 2026-05-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("model_tutorial", "0003_remove_user_post_post_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Author",
        ),
    ]
