# Generated by Django 6.0.2 on 2026-05-12 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("model_tutorial", "0004_rename_user_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="user",
            new_name="author",
        ),
    ]
