# Generated by Django 6.0.2 on 2026-05-12 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_tutorial", "0005_rename_user_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="model_tutorial.author",
            ),
            preserve_default=False,
        ),
    ]
