# Generated by Django 6.0.2 on 2026-04-19 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=20)),
                (
                    "student_age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(6),
                            django.core.validators.MaxValueValidator(30),
                        ]
                    ),
                ),
                ("student_email", models.EmailField(max_length=254, unique=True)),
                ("student_enrolled_date", models.DateField(auto_now_add=True)),
                ("student_info_updated", models.DateField(auto_now=True)),
            ],
        ),
    ]
