# Generated by Django 6.0.2 on 2026-06-01 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewsapp", "0002_category_products_is_active_products_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="category",
        ),
        migrations.AlterField(
            model_name="products",
            name="product_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="viewsapp.category",
            ),
        ),
    ]
