# Generated by Django 6.0.2 on 2026-06-01 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("viewsapp", "0003_remove_products_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="product_category",
            new_name="category",
        ),
    ]
