# Generated by Django 6.0.2 on 2026-06-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewsapp", "0004_rename_product_category_products_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
