# Generated by Django 6.0.2 on 2026-06-04 15:33

import viewsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewsapp", "0005_products_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product_images/",
                validators=[viewsapp.models.validate_image],
            ),
        ),
    ]
